export const BEGIN_FETCH_POSTS = 'BEGIN_FETCH_POSTS'
export const APPEND_POSTS = 'APPEND_POSTS'
export const BEGIN_FETCH_SINGLE_POST = 'BEGIN_FETCH_SINGLE_POST'
export const RECEIVE_SINGLE_POST = 'RECEIIVE_SINGLE_POST'
